### ISSUE TITLE
cannot build Mac 10.15.6 no key to match ID 93M47F4H9T

### ISSUE THREAD

**Issue by aldobranti** [rsyncOSX/rcloneosx#615] opened 2020-07-22 14:47 UTC
Trying to build on Catalina
transcript follows

$ make
xcodebuild -derivedDataPath /Users/will/Downloads/RsyncOSX-master -configuration Release -scheme RsyncOSX
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -derivedDataPath /Users/will/Downloads/RsyncOSX-master -configuration Release -scheme RsyncOSX

User defaults from command line:
    IDEDerivedDataPathOverride = /Users/will/Downloads/RsyncOSX-master

Resolve Package Graph

Fetching https://github.com/rsyncOSX/ShellOut.git

Cloning https://github.com/rsyncOSX/ShellOut.git

Checking out https://github.com/rsyncOSX/ShellOut.git at 2.3.0

Resolved source packages:
  ShellOut: https://github.com/rsyncOSX/ShellOut.git @ 2.3.0

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "93M47F4H9T" with a private key was found. (in target 'RsyncOSX' from project 'RsyncOSX')

** BUILD FAILED **

make: *** [release] Error 65

**Comment by rsyncOSX** [comment] 2020-07-26 13:24
Hi..

It seems like you are trying to build RsyncOSX, not RcloneOSX.. The issue is due to not having the private key for "93M47F4H9T", which is my developer ID. If you want to compile your own version, please [see here to remove the keys](https://rsyncosx.netlify.app/post/compile/). I am closing this issue due to wrong repository.

**Closed by rsyncOSX** 2020-07-26 13:24 UTC
